### ISSUE TITLE
Decifer compatibility

### ISSUE THREAD

**Issue by mkinnaman** [raphael-group/calder#7]
Hi!

I have longitudinal samples I am using decifer to cluster provide a DCF for. 

Is it possible to use Calder on the clusters by adjusting the DCF to represent a read count? I think it would need to be divided by 2 as Calder caps VAFs at 0.5 I believe?

Appreciate any insight.

Kind Regards,
Michael

**Comment by gsatas** [comment]
Hi Michael,

Yes, the simplest way to do this would be to scale the read counts of each mutation using the inferred cluster DCF divided by 2 (because CALDER assumes all mutations are in heterozygous diploid regions). So if a mutation has 100 reads and an inferred DCF of 40%, the corresponding input would have 20 variant reads and 80 reference reads.

We should soon have scripts to convert the output of DeCiFer into the input of other programs soon as well.

**Comment by mkinnaman** [comment]
Great - thank you!
